## Q1. Embedding the query

Embed the query: `'I just discovered the course. Can I join now?'`.
Use the `'jinaai/jina-embeddings-v2-small-en'` model. 

You should get a numpy array of size 512.

What's the minimal value in this array?

In [42]:
from fastembed import TextEmbedding

In [43]:
model_handle = "jinaai/jina-embeddings-v2-small-en"

In [44]:
embedding_model = TextEmbedding(model_handle)

In [45]:
embeddings_generator = embedding_model.embed('I just discovered the course. Can I join now?')

In [46]:
embeddings_list = list(embeddings_generator)

In [47]:
len(embeddings_list[0])

512

In [48]:
q = embeddings_list[0]
print(q.min())

-0.11726373885183883

## Cosine similarity

The vectors that our embedding model returns are already normalized: their length is 1.0.

You can check that by using the `norm` function:

```python
import numpy as np
np.linalg.norm(q)
```

Which means that we can simply compute the dot product between
two vectors to learn the cosine similarity between them.

For example, if you compute the cosine of the query vector with itself, the result will be 1.0:

```python
q.dot(q)
```

In [49]:
import numpy as np
np.linalg.norm(q)

np.float64(1.0)

In [50]:
q.dot(q)

np.float64(1.0000000000000002)

## Q2. Cosine similarity with another vector

Now let's embed this document:

```python
doc = 'Can I still join the course after the start date?'
```

What's the cosine similarity between the vector for the query
and the vector for the document?

* 0.3
* 0.5
* 0.7
* 0.9

In [51]:
doc = 'Can I still join the course after the start date?'

In [52]:
embeddings_generator = embedding_model.embed(doc)

In [53]:
embeddings_list = list(embeddings_generator)

In [54]:
doc_embedding = embeddings_list[0]

In [55]:
q.dot(doc_embedding)

np.float64(0.9008528895674548)

## Q3. Ranking by cosine

For Q3 and Q4 we will use these documents:

```python
documents = [{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'course': 'data-engineering-zoomcamp'}]
```

Compute the embeddings for the text field, and compute the 
cosine between the query vector and all the documents.

What's the document index with the highest similarity? (Indexing starts from 0):

- 0
- 1
- 2
- 3
- 4

Hint: if you put all the embeddings of the text field in one matrix `V` (a single 2-dimensional numpy array), then
computing the cosine becomes a matrix multiplication:

```python
V.dot(q)
```

If this hint is rather confusing you than helping, feel free
to ignore it.

In [56]:
documents = [{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'course': 'data-engineering-zoomcamp'}]

In [57]:
text_docs = [doc["text"] for doc in documents]

In [58]:
embeddings_generator = embedding_model.embed(text_docs)

In [59]:
V = np.array(list(embeddings_generator))

In [63]:
similartiy = V.dot(q)
similartiy

array([0.76296847, 0.81823782, 0.80853974, 0.7133079 , 0.73044992])

In [64]:
similartiy.argmax()

np.int64(1)

 index with the highest similarity is 1.

## Q4. Ranking by cosine, version two

Now let's calculate a new field, which is a concatenation of
`question` and `text`:

```python
full_text = doc['question'] + ' ' + doc['text']
``` 

Embed this field and compute the cosine between it and the
query vector. What's the highest scoring document?

- 0
- 1
- 2
- 3
- 4

Is it different from Q3? If yes, why?

In [75]:
import pandas as pd
df = pd.DataFrame(documents)
df

,text,section,question,course
0,"Yes, even if you don't register, you're still ...",General course-related questions,Course - Can I still join the course after the...,data-engineering-zoomcamp
1,"Yes, we will keep all the materials after the ...",General course-related questions,Course - Can I follow the course after it fini...,data-engineering-zoomcamp
2,The purpose of this document is to capture fre...,General course-related questions,Course - When will the course start?,data-engineering-zoomcamp
3,You can start by installing and setting up all...,General course-related questions,Course - What can I do before the course starts?,data-engineering-zoomcamp
4,Star the repo! Share it with friends if you fi...,General course-related questions,How can we contribute to the course?,data-engineering-zoomcamp

In [80]:
embeddings_generator = embedding_model.embed(df.question + ' ' + df.text)

In [81]:
V = np.array(list(embeddings_generator))

In [82]:
similartiy = V.dot(q)
similartiy

array([0.85145432, 0.84365942, 0.8408287 , 0.7755158 , 0.80860078])

In [83]:
similartiy.argmax()

np.int64(0)

 index with the highest similarity is 0 now.

## Q5. Selecting the embedding model

Now let's select a smaller embedding model.
What's the smallest dimensionality for models in fastembed?

- 128
- 256
- 384
- 512

One of these models is `BAAI/bge-small-en`. Let's use it.

Smallest dimensionality for models in fastembed is 384 Models like BAAI/bge-small-en.

## Q6. Indexing with qdrant (2 points)

For the last question, we will use more documents.

We will select only FAQ records from our ml zoomcamp:

```python
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()


documents = []

for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)
```

Add them to qdrant using the model form Q5.

When adding the data, use both question and answer fields:

```python
text = doc['question'] + ' ' + doc['text']
```

After the data is inserted, use the question from Q1 for querying the collection.

What's the highest score in the results?
(The score for the first returned record):

- 0.97
- 0.87
- 0.77
- 0.67

In [84]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()


documents = []

for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [85]:
documents

[{'text': 'Machine Learning Zoomcamp FAQ\nThe purpose of this document is to capture frequently asked technical questions.\nWe did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:\nData Engineering Zoomcamp FAQ\nIn the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo\nwork',
  'section': 'General course-related questions',
  'question': 'How do I sign up?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'The course videos are pre-recorded, you can start watching the course right now.\nWe will also occasionally have office hours - live sessions where we will answer your questions. The office hours sessions are recorded too.\nYou can see the office hours as well as the pre-recorded course videos in the course playlist on YouTube.',
  'section': 'General course-related questions',
  'question': 'Is it going to be live? When?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Everything is recorded, so you won’t miss anything. You will be able to ask your questions for office hours in advance and we will cover them during the live stream. Also, you can always ask questions in Slack.',
  'section': 'General course-related questions',
  'question': 'What if I miss a session?',
  'course': 'machine-learning-zoomcamp'},
 {'text': "The bare minimum. The focus is more on practice, and we'll cover the theory only on the intuitive level.: https://mlbookcamp.com/article/python\nFor example, we won't derive the gradient update rule for logistic regression (there are other great courses for that), but we'll cover how to use logistic regression and make sense of the results.",
  'section': 'General course-related questions',
  'question': 'How much theory will you cover?',
  'course': 'machine-learning-zoomcamp'},
 {'text': "Yes! We'll cover some linear algebra in the course, but in general, there will be very few formulas, mostly code.\nHere are some interesting videos covering linear algebra that you can already watch: ML Zoomcamp 1.8 - Linear Algebra Refresher from Alexey Grigorev or the excellent playlist from 3Blue1Brown Vectors | Chapter 1, Essence of linear algebra. Never hesitate to ask the community for help if you have any question.\n(Mélanie Fouesnard)",
  'section': 'General course-related questions',
  'question': "I don't know math. Can I take the course?",
  'course': 'machine-learning-zoomcamp'},
 {'text': "The process is automated now, so you should receive the email eventually. If you haven’t, check your promotions tab in Gmail as well as spam.\nIf you unsubscribed from our newsletter, you won't get course related updates too.\nBut don't worry, it’s not a problem. To make sure you don’t miss anything, join the #course-ml-zoomcamp channel in Slack and our telegram channel with announcements. This is enough to follow the course.",
  'section': 'General course-related questions',
  'question': "I filled the form, but haven't received a confirmation email. Is it normal?",
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Approximately 4 months, but may take more if you want to do some extra activities (an extra project, an article, etc)',
  'section': 'General course-related questions',
  'question': 'How long is the course?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Around ~10 hours per week. Timur Kamaliev did a detailed analysis of how much time students of the previous cohort needed to spend on different modules and projects. Full article',
  'section': 'General course-related questions',
  'question': 'How much time do I need for this course?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Yes, if you finish at least 2 out of 3 projects and review 3 peers’ Projects by the deadline, you will get a certificate. This is what it looks like: link. There’s also a version without a robot: link.',
  'section': 'General course-related questions',
  'question': 'Will I get a certificate?',
  'course': 'machine-learning-zoomcamp'},
 {'text': "Yes, it's possible. See the previous answer.",
  'section': 'General course-related questions',
  'question': 'Will I get a certificate if I missed the midterm project?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Check this article. If you know everything in this article, you know enough. If you don’t, read the article and join the coursIntroduction to Pythone too :)\nIntroduction to Python – Machine Learning Bookcamp\nYou can follow this English course from the OpenClassrooms e-learning platform, which is free and covers the python basics for data analysis: Learn Python Basics for Data Analysis - OpenClassrooms . It is important to know some basics such as: how to run a Jupyter notebook, how to import libraries (and what libraries are), how to declare a variable (and what variables are) and some important operations regarding data analysis.\n(Mélanie Fouesnard)',
  'section': 'General course-related questions',
  'question': 'How much Python should I know?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'For the Machine Learning part, all you need is a working laptop with an internet connection. The Deep Learning part is more resource intensive, but for that you can use a cloud (we use Saturn cloud but can be anything else).\n(Rileen Sinha; based on response by Alexey on Slack)',
  'section': 'General course-related questions',
  'question': "Any particular hardware requirements for the course or everything is mostly cloud? TIA! Couldn't really find this in the FAQ.",
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Here is an article that worked for me: https://knowmledge.com/2023/12/07/ml-zoomcamp-2023-project/',
  'section': 'General course-related questions',
  'question': 'How to setup TensorFlow with GPU support on Ubuntu?',
  'course': 'machine-learning-zoomcamp'},
 {'text': "Here’s how you join a in Slack: https://slack.com/help/articles/205239967-Join-a-channel\nClick “All channels” at the top of your left sidebar. If you don't see this option, click “More” to find it.\nBrowse the list of public channels in your workspace, or use the search bar to search by channel name or description.\nSelect a channel from the list to view it.\nClick Join Channel.\nDo we need to provide the GitHub link to only our code corresponding to the homework questions?\nYes. You are required to provide the URL to your repo in order to receive a grade",
  'section': 'General course-related questions',
  'question': 'I’m new to Slack and can’t find the course channel. Where is it?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.',
  'section': 'General course-related questions',
  'question': 'The course has already started. Can I still join it?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'The course is available in the self-paced mode too, so you can go through the materials at any time. But if you want to do it as a cohort with other students, the next iterations will happen in September 2023, September 2024 (and potentially other Septembers as well).',
  'section': 'General course-related questions',
  'question': 'When does the next iteration start?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'No, it’s not possible. The form is closed after the due date. But don’t worry, homework is not mandatory for finishing the course.',
  'section': 'General course-related questions',
  'question': 'Can I submit the homework after the due date?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Welcome to the course! Go to the course page (http://mlzoomcamp.com/), scroll down and start going through the course materials. Then read everything in the cohort folder for your cohort’s year.\nClick on the links and start watching the videos. Also watch office hours from previous cohorts. Go to DTC youtube channel and click on Playlists and search for {course yyyy}. ML Zoomcamp was first launched in 2021.\nOr you can just use this link: http://mlzoomcamp.com/#syllabus',
  'section': 'General course-related questions',
  'question': 'I just joined. What should I do next? How can I access course materials?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'For the 2023 cohort, you can see the deadlines here (it’s taken from the 2023 cohort page)',
  'section': 'General course-related questions',
  'question': 'What are the deadlines in this course?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'There’s not much difference. There was one special module (BentoML) in the previous iteration of the course, but the rest of the modules are the same as in 2022. The homework this year is different.',
  'section': 'General course-related questions',
  'question': 'What’s the difference between the previous iteration of the course (2022) and this one (2023)?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'We won’t re-record the course videos. The focus of the course and the skills we want to teach remained the same, and the videos are still up-to-date.\nIf you haven’t taken part in the previous iteration, you can start watching the videos. It’ll be useful for you and you will learn new things. However, we recommend using Python 3.10 now instead of Python 3.8.',
  'section': 'General course-related questions',
  'question': 'The course videos are from the previous iteration. Will you release new ones or we’ll use the videos from 2021?',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'When you post about what you learned from the course on your social media pages, use the tag #mlzoomcamp. When you submit your homework, there’s a section in the form for putting the links there. Separate multiple links by any whitespace character (linebreak, space, tab, etc).\nFor posting the learning in public links, you get extra scores. But the number of scores is limited to 7 points: if you put more than 7 links in your homework form, you’ll get only 7 points.\nThe same content can be posted to 7 different social sites and still earn you 7 points if you add 7 URLs per week, see Alexey’s reply. (~ ellacharmed)\nFor midterms/capstones, the awarded points are doubled as the duration is longer. So for projects the points are capped at 14 for 14 URLs.',
  'section': 'General course-related questions',
  'question': 'Submitting learning in public links',
  'course': 'machine-learning-zoomcamp'},
 {'text': "You can create your own github repository for the course with your notes, homework, projects, etc.\nThen fork the original course repo and add a link under the 'Community Notes' section to the notes that are in your own repo.\nAfter that's done, create a pull request to sync your fork with the original course repo.\n(By Wesley Barreto)",
  'section': 'General course-related questions',
  'question': 'Adding community notes',
  'course': 'machine-learning-zoomcamp'},
 {'text': "Leaderboard Links:\n2023 - https://docs.google.com/spreadsheets/d/e/2PACX-1vSNK_yGtELX1RJK1SSRl4xiUbD0XZMYS6uwHnybc7Mql-WMnMgO7hHSu59w-1cE7FeFZjkopbh684UE/pubhtml\n2022 - https://docs.google.com/spreadsheets/d/e/2PACX-1vQzLGpva63gb2rIilFnpZMRSb-buyr5oGh8jmDtIb8DANo4n6hDalra_WRCl4EZwO1JvaC4UIS62n5h/pubhtml\nPython Code:\nfrom hashlib import sha1\ndef compute_hash(email):\nreturn sha1(email.lower().encode('utf-8')).hexdigest()\nYou need to call the function as follows:\nprint(compute_hash('YOUR_EMAIL_HERE'))\nThe quotes are required to denote that your email is a string.\n(By Wesley Barreto)\nYou can also use this website directly by entering your email: http://www.sha1-online.com. Then, you just have to copy and paste your hashed email in the “research” bar of the leaderboard to get your scores.\n(Mélanie Fouesnard)",
  'section': '1. Introduction to Machine Learning',
  'question': 'Computing the hash for the leaderboard and project review',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'If you get “wget is not recognized as an internal or external command”, you need to install it.\nOn Ubuntu, run\nsudo apt-get install wget\nOn Windows, the easiest way to install wget is to use Chocolatey:\nchoco install wget\nOr you can download a binary from here and put it to any location in your PATH (e.g. C:/tools/)\nOn Mac, the easiest way to install wget is to use brew.\nBrew install wget\nAlternatively, you can use a Python wget library, but instead of simply using “wget” you’ll need eeeto use\npython -m wget\nYou need to install it with pip first:\npip install wget\nAnd then in your python code, for example in your jupyter notebook, use:\nimport wget\nwget.download("URL")\nThis should download whatever is at the URL in the same directory as your code.\n(Memoona Tahira)\nAlternatively, you can read a CSV file from a URL directly with pandas:\nurl = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"\ndf = pd.read_csv(url)\nValid URL schemes include http, ftp, s3, gs, and file.\nIn some cases you might need to bypass https checks:\nimport ssl\nssl._create_default_https_context = ssl._create_unverified_context\nOr you can use the built-in Python functionality for downloading the files:\nimport urllib.request\nurl = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"\nurllib.request.urlretrieve(url, "housing.csv")\nUrllib.request.urlretrieve() is a standard Python library function available on all devices and platforms. URL requests and URL data retrieval are done with the urllib.request module.\nThe urlretrieve() function allows you to download files from URLs and save them locally. Python programs use it to download files from the internet.\nOn any Python-enabled device or platform, you can use the urllib.request.urlretrieve() function to download the file.\n(Mohammad Emad Sharifi)',
  'section': '1. Introduction to Machine Learning',
  'question': 'wget is not recognized as an internal or external command',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'You can use\n!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv\nTo download the data too. The exclamation mark !, lets you execute shell commands inside your notebooks. This works generally for shell commands such as ls, cp, mkdir, mv etc . . .\nFor instance, if you then want to move your data into a data directory alongside your notebook-containing directory, you could execute the following:\n!mkdir -p ../data/\n!mv housing.csv ../data/',
  'section': '1. Introduction to Machine Learning',
  'question': 'Retrieving csv inside notebook',
  'course': 'machine-learning-zoomcamp'},
 {'text': '(Tyler Simpson)',
  'section': '1. Introduction to Machine Learning',
  'question': 'Windows WSL and VS Code\nIf you have a Windows 11 device and would like to use the built in WSL to access linux you can use the Microsoft Learn link Set up a WSL development environment | Microsoft Learn. To connect this to VS Code download the Microsoft verified VS Code extension ‘WSL’ this will allow you to remotely connect to your WSL Ubuntu instance as if it was a virtual machine.',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'This is my first time using Github to upload a code. I was getting the below error message when I type\ngit push -u origin master:\nerror: src refspec master does not match any\nerror: failed to push some refs to \'https://github.com/XXXXXX/1st-Homework.git\'\nSolution:\nThe error message got fixed by running below commands:\ngit commit -m "initial commit"\ngit push origin main\nIf this is your first time to use Github, you will find a great & straightforward tutorial in this link https://dennisivy.com/github-quickstart\n(Asia Saeed)\nYou can also use the “upload file” functionality from GitHub for that\nIf you write your code on Google colab you can also directly share it on your Github.\n(By Pranab Sarma)',
  'section': '1. Introduction to Machine Learning',
  'question': 'Uploading the homework to Github',
  'course': 'machine-learning-zoomcamp'},
 {'text': "I'm trying to invert the matrix but I got error that the matrix is singular matrix\nThe singular matrix error is caused by the fact that not every matrix can be inverted. In particular, in the homework it happens because you have to pay close attention when dealing with multiplication (the method .dot) since multiplication is not commutative! X.dot(Y) is not necessarily equal to Y.dot(X), so respect the order otherwise you get the wrong matrix.",
  'section': '1. Introduction to Machine Learning',
  'question': 'Singular Matrix Error',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'I have a problem with my terminal. Command\nconda create -n ml-zoomcamp python=3.9\ndoesn’t work. Any of 3.8/ 3.9 / 3.10 should be all fine\nIf you’re on Windows and just installed Anaconda, you can use Anaconda’s own terminal called “Anaconda Prompt”.\nIf you don’t have Anaconda or Miniconda, you should install it first\n(Tatyana Mardvilko)',
  'section': '1. Introduction to Machine Learning',
  'question': 'Conda is not an internal command',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'How do I read the dataset with Pandas in Windows?\nI used the code below but not working\ndf = pd.read_csv(\'C:\\Users\\username\\Downloads\\data.csv\')\nUnlike Linux/Mac OS, Windows uses the backslash (\\) to navigate the files that cause the conflict with Python. The problem with using the backslash is that in Python, the \'\\\' has a purpose known as an escape sequence. Escape sequences allow us to include special characters in strings, for example, "\\n" to add a new line or "\\t" to add spaces, etc. To avoid the issue we just need to add "r" before the file path and Python will treat it as a literal string (not an escape sequence).\nHere’s how we should be loading the file instead:\ndf = pd.read_csv(r\'C:\\Users\\username\\Downloads\\data.csv\')\n(Muhammad Awon)',
  'section': '1. Introduction to Machine Learning',
  'question': 'Read-in the File in Windows OS',
  'course': 'machine-learning-zoomcamp'},
 {'text': 'Type the following command:\ngit config -l | grep url\nThe output should look like this:\nremote.origin.url=https://github.com/github-username/github-repository-name.git\nChange this to the following format and make sure the change is reflected using command in step 1:\ngit remote set-url origin "https://github-username@github.com/github-username/github-repository-name.git"\n(Added by Dheeraj Karra)',
  'section': '1. Introduction to Machine Learning',
  'question': "'403 Forbidden' error message when you try to push to a GitHub repository",
  'course': 'machine-learning-zoomcamp'},
 {'text': "I had a problem when I tried to push my code from Git Bash:\nremote: Support for password authentication was removed on August 13, 2021.\nremote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.\nfatal: Authentication failed for 'https://github.com/username\nSolution:\nCreate a personal access token from your github account and use it when you make a push of your last changes.\nhttps://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent\nBruno Bedón",
  'section': '1. Introduction to Machine Learning',
  'question': "Fatal: Authentication failed for 'https://github.com/username",
  'course': 'machine-learning-zoomcamp'},

In [86]:
df = pd.DataFrame(documents)
df

,text,section,question,course
0,Machine Learning Zoomcamp FAQ\nThe purpose of ...,General course-related questions,How do I sign up?,machine-learning-zoomcamp
1,"The course videos are pre-recorded, you can st...",General course-related questions,Is it going to be live? When?,machine-learning-zoomcamp
2,"Everything is recorded, so you won’t miss anyt...",General course-related questions,What if I miss a session?,machine-learning-zoomcamp
3,The bare minimum. The focus is more on practic...,General course-related questions,How much theory will you cover?,machine-learning-zoomcamp
4,Yes! We'll cover some linear algebra in the co...,General course-related questions,I don't know math. Can I take the course?,machine-learning-zoomcamp
...,...,...,...,...
370,You can consider several different approaches:...,Miscellaneous,"How can I work with very large datasets, e.g. ...",machine-learning-zoomcamp
371,"Technically, yes. Advisable? Not really. Reaso...",Miscellaneous,"Can I do the course in other languages, like R...",machine-learning-zoomcamp
372,"Yes, it’s allowed (as per Alexey).\nAdded By R...",Miscellaneous,Is use of libraries like fast.ai or huggingfac...,machine-learning-zoomcamp
373,The TF and TF Serving versions have to match (...,Miscellaneous,"Flask image was built and tested successfully,...",machine-learning-zoomcamp
374,I’ve seen LinkedIn users list DataTalksClub as...,Miscellaneous,Any advice for adding the Machine Learning Zoo...,machine-learning-zoomcamp

In [88]:
from qdrant_client import QdrantClient, models
qd_client = QdrantClient("http://localhost:6333")

In [89]:
EMBEDDING_DIMENSIONALITY = 384
model_handle = "BAAI/bge-small-en"
collection_name = "llmzoomcamp-homework"

In [90]:
qd_client.delete_collection(collection_name=collection_name)

qd_client.create_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=EMBEDDING_DIMENSIONALITY,
        distance=models.Distance.COSINE
    )
)

True

In [91]:
points = []

for i, doc in enumerate(documents):
    text = doc['question'] + ' ' + doc['text']
    vector = models.Document(text=text, model=model_handle)
    point = models.PointStruct(
        id=i,
        vector=vector,
        payload=doc
    )
    points.append(point)

qd_client.upsert(
    collection_name=collection_name,
    points=points
)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [92]:
question = 'I just discovered the course. Can I join now?'

query_points = qd_client.query_points(
    collection_name=collection_name,
    query=models.Document(
        text=question,
        model=model_handle 
    ),
    limit=5,
    with_payload=True
)

In [93]:
query_points.points[0]

ScoredPoint(id=14, version=1, score=0.8703172, payload={'text': 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.', 'section': 'General course-related questions', 'question': 'The course has already started. Can I still join it?', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None)

The highest score in the results is 0.87.